### ISSUE TITLE
Text shadow on multiple lines with IE9, IE7, IE6 (IE8 not tested)

### ISSUE THREAD

**Issue by jocelynlecomte** [heygrady/textshadow#1] opened 2012-01-23 15:23 UTC
When the shadowed text contains a '-' char, the shadow takes 2 lines instead of one.

**Comment by heygrady** [comment] 2012-01-23 18:14
Please paste in an example. That will save me time.

**Comment by jocelynlecomte** [comment] 2012-01-26 14:11
Here is a link: http://pastebin.com/543hvyaV

**Comment by heygrady** [comment] 2012-01-27 00:17
The example really helped. I just committed a fix that takes IE breakword characters into account so this should fix a variety of situations including your issue. Thanks for bringing this to my attention.

In the future, it's even more useful to use http://jsfiddle.net/ when trying to report issues you find. Most developers respond better when a bug is accompanied by a test case that makes it easy to see what the issue is.

**Closed as completed by heygrady** 2012-01-27 00:17 UTC

**Comment by jocelynlecomte** [comment] 2012-01-27 08:46
I tried with jsfiddle for hours, but I couldn't make it work with the additional jquery.textshadow libraries... Do you have a link to a fiddle that does it ?

**Comment by heygrady** [comment] 2012-01-27 18:01
You can usually just cut and paste the library into the JS box. It makes it easier to minify the files before pasting it with a tool like http://marijnhaverbeke.nl/uglifyjs You can also sometimes get it to work by linking to the raw file hosted on GitHub. But IE has troubles with that method.

Let me know if you have further troubles with the text-shadow code.
